spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        check_nullability: true
        use_sql_comments: true # 어떤 쿼리를 실행하는 지 힌트 표시
        format_sql: true # 쿼리를 가독성 있게 출력
        show_sql: true # 쿼리 출력