spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  jwt:
    token:
      secret-key: housepit#12%^!!Tzc@8924
      access-token-expire-time: 5 # 5min
      refresh-token-expire-time: 43200 # 1mo


