security:
  jwt:
    token:
      secret-key: housepit#12%^!!Tzc@8924
      access-token-expire-time: 5 # 5min
      refresh-token-expire-time: 43200 # 1mo
grpc:
  server:
    port: 12345
server:
  port: 8081
