security:
  jwt:
    token:
      secret-key: housepit#123
      access-token-expire-time: 5 # 5min
      refresh-token-expire-time: 43200 # 1mo
server:
  port: 8081
grpc:
  server:
    port: 50051
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:common/sql/mysql/schema.sql
      data-locations: classpath:common/sql/data.sql
  datasource:
    url: 'jdbc:h2:mem:authentication;MODE=MySQL;DATABASE_TO_UPPER=false'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        check_nullability: true
        use_sql_comments: true
        format_sql: true
        show_sql: true