create table member (
      id bigint generated by default as identity,
      member_uuid varchar(255) not null,
      user_name varchar(255) not null,
      phone varchar(255) not null,
      ci varchar(255) not null,
      created_at timestamp,
      created_by varchar(255),
      modified_date timestamp,
      last_modified_at timestamp,
      last_modified_by varchar(255),
      primary key (id),
      unique (uuid)
);

create table member_social_login (
        id bigint generated by default as identity,
        provider varchar(255) not null,
        email varchar(255) not null,
        created_at timestamp,
        created_by varchar(255),
        modified_date timestamp,
        last_modified_at timestamp,
        last_modified_by varchar(255),
        primary key (id)
);

create table member_role (
     id bigint generated by default as identity,
     role varchar(100) not null,
     created_at timestamp,
     created_by varchar(255),
     modified_date timestamp,
     last_modified_at timestamp,
     last_modified_by varchar(255),
     primary key (id)
);
